#pragma once

#include <cstdint>

// Auto-generated by firmware/tools/gen_object_pool.py -- do not hand-edit.
// Object ID constants matching object_pool.iop. See docs/vt-ui-design.md.

namespace iso::object_pool_ids {

constexpr uint16_t kWorkingSet = 1000;
constexpr uint16_t kDataMask = 1100;
constexpr uint16_t kSoftKeyMask = 1200;
constexpr uint16_t kSoftKeyMask2 = 1201;
constexpr uint16_t kTitleString = 1101;
constexpr uint16_t kTitleStringMaxChars = 44;

// channel: 1-8
inline uint16_t relay_rect_id(int channel) { return 1110 + channel; }
inline uint16_t relay_fill_attr_id(int channel) { return 1920 + channel; }
inline uint16_t relay_label_id(int channel) { return 1120 + channel; }
inline uint16_t di_fill_attr_id(int channel) { return 1930 + channel; }

// key_number: 1-8 = relay channels (toggle), 9 = buzzer, 10 = next page
inline uint16_t softkey_id(int key_number) { return 1210 + key_number; }

// Soft Key Mask page 2: channel 1-8 = momentary override, plus a back key.
inline uint16_t softkey2_id(int channel) { return 1250 + channel; }
constexpr uint16_t kSoftkeyBack = 1260;

// AUX-N Auxiliary Function Type 2 objects. channel: 1-8.
inline uint16_t aux_latch_function_id(int channel) { return 1500 + channel; }
inline uint16_t aux_momentary_function_id(int channel) { return 1520 + channel; }
constexpr uint16_t kAuxBuzzerFunction = 1560;

}  // namespace iso::object_pool_ids
