#pragma once

#include <cstdint>

// Auto-generated by firmware/tools/gen_object_pool.py -- do not hand-edit.
// Object ID constants matching object_pool.iop. See docs/vt-ui-design.md.

namespace iso::object_pool_ids {

constexpr uint16_t kWorkingSet = 1000;
constexpr uint16_t kDataMask = 1100;
constexpr uint16_t kSoftKeyMask = 1200;

// channel: 1-8
inline uint16_t relay_rect_id(int channel) { return 1110 + channel; }
inline uint16_t relay_fill_attr_id(int channel) { return 1920 + channel; }

// key_number: 1-8 = relay channels, 9 = buzzer
inline uint16_t softkey_id(int key_number) { return 1210 + key_number; }

}  // namespace iso::object_pool_ids
